apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: python app deployed on kubernetes cluster
  annotations:
    github.com/project-slug: vinaysingh19/python-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental